sudo: required
services:
  - docker
language: node_js
node_js:
  - '6'
  - '8'
addons:
  apt:
    packages: rpm
install:
  - make prepare
before_script:
  - gem install fpm
script:
  - make build
  - make docker_image
  - make docker_push_release
